stages:
  - build


build:
  stage: build
  image: ttl.sh/dagger-go-oc:latest
  tags:
    - buildkit-test
  variables:
    "_EXPERIMENTAL_DAGGER_RUNNER_HOST": "unix:///var/run/dagger/buildkitd.sock"
  script:
  - printenv
  - dagger run go run ci/main.go
  - echo "Yallah!"
