stages:
  - build


build:
  stage: build
  image: ttl.sh/dagger-go-oc:latest
  variables:
    "_EXPERIMENTAL_DAGGER_RUNNER_HOST": "kube-pod://buildkitd-6f9bbc8677-f7jlt"
  script:
  - oc login --token=$TOKEN --server=https://api.ocp-staging.cloudscale.puzzle.ch:6443
  - oc project pitc-buildkit-test
  - oc get pods
  - printenv
  - dagger run go run ci/main.go
  - echo "Yallah!"
